Impression.create!([
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "b493d70d08ddca681ce5d2747bdc0755c1589e5b9c1605e43daeb3be3a5d0671", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "b493d70d08ddca681ce5d2747bdc0755c1589e5b9c1605e43daeb3be3a5d0671", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "920a7b204aa616aa2a0b85644a7e88fc76c92bf654a725b9fa592635a22633ea", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: "http://localhost:3000/posts", params: {}},
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "30a265ed84bbab414ade4ca7512000b7cb2857a052746eaf3eccaee221cdecc0", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "f621113f5cf3d4690555b7b7034c833d715e88eac25fe778fc8ea96614900578", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 7, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "a486ac0d8cad969f9f70e06476e10d9b79477d210ce52dcd56c7422017fa4773", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: "http://localhost:3000/posts", params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "d22d03787be1e0ae2b12d12acead4ffcdde4868de8867a9215bedf612b5d6a1f", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: "http://localhost:3000/posts", params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "0640467baa28b1d02b3101ad1dcebfadd7964c228f9aa788a3ea6bb0535673d9", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "644b9aa08a77697b08613cff5e8b2bf9e27f0638abb467fffe765d90f8403c1c", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: "http://localhost:3000/posts", params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "77fe57d2d35f2b0c5a1850feb80260c0ec9b5d8bd0ef50ce8c1ee080630b5916", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "38dd1535cda335fd0a8ac228fe1acf50bf03e2fb74f07f07ecbd3f13741485e3", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "573bc2ba0378123ae9fb405d095348e76f9faeb92d89dc87b6d3215acd4f7371", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}},
  {impressionable_type: "Post", impressionable_id: 1, user_id: nil, controller_name: "posts", action_name: "show", view_name: nil, request_hash: "326f6570479f4a4d071ea6ed3e27741aaf941c1ad1cb03c5b97bcc3ef2be80cc", ip_address: "127.0.0.1", session_hash: "09d56733dcdb24647765bb50067d5742", message: nil, referrer: nil, params: {}}
])
Admin.create!([
  {name: "Abayo", email: "luc.bayo@gmail.com", password_digest: "$2a$10$dDXx8HLn44cx0dXn8qKDqeHECl.G8qGH95DLpqPwPpSPSUtj6SdKS", identity: "1199580072604146"},
  {name: "Abayo", email: "luc.bayo@gmail.com", password_digest: "$2a$10$dDXx8HLn44cx0dXn8qKDqeHECl.G8qGH95DLpqPwPpSPSUtj6SdKS", identity: "1199580072604146"}
])
Comment.create!([
  {name: "Joseph ", email: "joseph@example.com", body: "I wanna test", web: "www.nexpals.info", post_id: 1},
  {name: "Joseph ", email: "muganezajoseph@gmail.com", body: "This is working kbs", web: "", post_id: 7},
  {name: "Muta Nara", email: "narcisse@gmail.com", body: "Woa bro it works", web: "www.nexpals.info", post_id: 7},
  {name: "Joseph Mugwaneza", email: "muganezajoseph@gmail.com", body: "This awosom", web: "www.nexpals.info", post_id: 7},
  {name: "Nara", email: "nara@gmail.com", body: "cool", web: "nexplas", post_id: 7},
  {name: "luc", email: "luc@example.com", body: "Hello world", web: "www.exammple.com", post_id: nil},
  {name: "Joseph", email: "joseph@example.com", body: "Hello Rwanda", web: "www.nexpals.info", post_id: 2},
  {name: "Josh", email: "josh@example.com", body: "Cool", web: "www.nexpals.info", post_id: 1},
  {name: "Nara", email: "nara@example.com", body: "I see", web: "www.nexpals.info", post_id: 1},
  {name: "Jean Luc", email: "luc.bayo@nexpals.com", body: "I seee", web: "www.nexpals.info", post_id: 1},
  {name: "luc", email: "luc@example.com", body: "Hello world", web: "www.exammple.com", post_id: nil},
  {name: "Joseph", email: "joseph@example.com", body: "Hello Rwanda", web: "www.nexpals.info", post_id: 2},
  {name: "Josh", email: "josh@example.com", body: "Cool", web: "www.nexpals.info", post_id: 1},
  {name: "Nara", email: "nara@example.com", body: "I see", web: "www.nexpals.info", post_id: 1},
  {name: "Jean Luc", email: "luc.bayo@nexpals.com", body: "I seee", web: "www.nexpals.info", post_id: 1}
])
Post.create!([
  {title: "Where can I get some?", body: "<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don&#39;t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn&#39;t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>\r\n\r\n<form action=\"http://www.lipsum.com/feed/html\" method=\"post\">\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:100%\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td rowspan=\"2\"><input name=\"amount\" size=\"3\" type=\"text\" value=\"5\" /></td>\r\n\t\t\t<td rowspan=\"2\">\r\n\t\t\t<table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n\t\t\t\t<tbody>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td><input checked=\"checked\" name=\"what\" type=\"radio\" value=\"paras\" /></td>\r\n\t\t\t\t\t\t<td>paragraphs</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td><input name=\"what\" type=\"radio\" value=\"words\" /></td>\r\n\t\t\t\t\t\t<td>words</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td><input name=\"what\" type=\"radio\" value=\"bytes\" /></td>\r\n\t\t\t\t\t\t<td>bytes</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td><input name=\"what\" type=\"radio\" value=\"lists\" /></td>\r\n\t\t\t\t\t\t<td>lists</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</tbody>\r\n\t\t\t</table>\r\n\t\t\t</td>\r\n\t\t\t<td><input checked=\"checked\" name=\"start\" type=\"checkbox\" value=\"yes\" /></td>\r\n\t\t\t<td>Start with &#39;Lorem<br />\r\n\t\t\tipsum dolor sit amet...&#39;</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td><input name=\"generate\" type=\"submit\" value=\"Generate Lorem Ipsum\" /></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n</form>\r\n", intro: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source."},
  {title: "What is Lorem Ipsum?", body: "<p><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n", intro: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."},
  {title: "Hello World", body: "Come on", intro: "This is it"},
  {title: "Hello World", body: "Come on", intro: "This is it"}
])
